baseURL: "https://hcenge.github.io/"
title: Helen Engelhardt
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Helen Engelhardt
  description: "Helen Engelhardt's personal website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: true
    title: "Helen Engelhardt"
    subtitle: "Hi! I'm a DPhil student at the University of Oxford, working in the Energy Materials Interface group under the supervision of Dr. Robert Weatherup. I recently graduated from the University of Waterloo with a BASc in Nanotechnology Engineering with Honours.
    \n\n\n I'm passionate about tech solutions to the climate crisis, specifically in the area of nanomaterials and electrochemistry. My current research focuses on the development of earth-abundant catalysts for the Oxygen Evolution Reaction to enable sustainable hydrogen production.
    \n\n\n I was in a co-op program in undergrad, and spent time in both industry and research. In brief, I've worked on gold nanoparticles for CO2 electrochemistry, battery materials, microfluidics for vaccine manufacturing, and battery recycling.
    \n\n\n When I'm not in the lab, you might find me hiking, playing violin, or knitting a sweater."
    imageUrl: "https://emi.web.ox.ac.uk/sites/default/files/styles/mt_image_medium_square/public/emi/images/media/thumbnail_53584129616_3ece17366a_o.jpg"
    imageTitle: "Profile Picture"
    imageWidth: 200
    imageHeight: 200
    # buttons:
    #   - name: CV
    #     url: "/cv"
    #   - name: Research
    #     url: "/research"

  assets:
    disableHLJS: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Helen Engelhardt"

  # home-info mode
  homeInfoParams:
    Title: "Helen Engelhardt"

  footer:
    hideCredits: true

  socialIcons:
    - name: github
      url: "https://github.com/hcenge"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=FWQCq3MAAAAJ&hl=en"
    - name: linkedin
      url: "https://www.linkedin.com/in/helen-engelhardt/"
    - name: orcid
      url: "https://orcid.org/0000-0001-6347-6194"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: cv
      name: CV
      url: /cv/
      weight: 10
    - identifier: research
      name: Research
      url: /research/
      weight: 20

